version: '3'

services:
  
  postgres:
    container_name: postgres
    image: postgres:12.0-alpine
    logging:
      driver: none
    #volumes:
    #  - ./postgres:/var/lib/postgresql/data:rw
    #ports:
    #  - 5432:5432
    environment:
      POSTGRES_DB: db
      POSTGRES_USER: user
      POSTGRES_PASSWORD: pass
  
  redis:
    container_name: redis
    image: redis:6.0-alpine
    logging:
      driver: none
    #volumes:
    #  - ./redis:/data:rw

  django:
#    restart: always
    container_name: django
    build: ./
    entrypoint: ./entrypoint.sh
    volumes:
      - ./logs:/logs
      - ./src:/src:rw
      - ./django.env:/src/core/.env
      - ./media:/src/media
      - ./gunicorn.conf.py:/src/gunicorn.conf.py
      - ./static:/src/staticfiles
    environment:
      MODE: DEV
    depends_on:
      - redis
      - postgres

  celery:
#    restart: always
    container_name: celery
    build: ./
    entrypoint: ./entrypoint.sh
    volumes:
      - ./src:/src:rw
      - ./django.env:/src/core/.env
    depends_on:
      - redis
    environment:
      MODE: CELERY
      
  
  nginx_dev:
    container_name: nginx
    image: nginx:1-alpine
    environment:
      - TZ=Asia/Almaty
    depends_on:
      - django
    volumes:
      - ./deploy/dev:/etc/nginx/conf.d
      - ./static:/staticfiles
      - ./media:/media
    ports:
      - "8000:8000"

