# Generated by Django 2.2.9 on 2020-07-26 00:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stream', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='stream',
            name='currency',
            field=models.CharField(blank=True, choices=[('KZT', 'KZT'), ('RUB', 'RUB'), ('USD', 'USD')], max_length=250, null=True, verbose_name='Статус'),
        ),
        migrations.AddField(
            model_name='stream',
            name='ticket_cost',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
