# Generated by Django 2.2.9 on 2020-07-26 00:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stream', '0002_auto_20200726_0014'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stream',
            name='currency',
            field=models.CharField(blank=True, choices=[('KZT', 'KZT'), ('RUB', 'RUB'), ('USD', 'USD')], default='KZT', max_length=250, null=True, verbose_name='currency'),
        ),
        migrations.AlterField(
            model_name='stream',
            name='ticket_cost',
            field=models.FloatField(blank=True, null=True, verbose_name='ticket cost'),
        ),
        migrations.AlterField(
            model_name='stream',
            name='title',
            field=models.CharField(blank=True, max_length=1023, null=True, verbose_name='title'),
        ),
        migrations.AlterField(
            model_name='stream',
            name='url',
            field=models.CharField(blank=True, max_length=1023, null=True, verbose_name='URL'),
        ),
    ]
