# Generated by Django 2.2.9 on 2020-07-26 03:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('stream', '0003_auto_20200726_0015'),
    ]

    operations = [
        migrations.CreateModel(
            name='Code',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(db_index=True, max_length=255, verbose_name='Code')),
                ('email', models.CharField(blank=True, max_length=255, null=True, verbose_name='Email')),
                ('stream', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='codes', to='stream.Stream', verbose_name='Stream')),
            ],
        ),
    ]
