# Generated by Django 2.2.9 on 2020-07-28 05:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stream', '0005_auto_20200728_0514'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='stream',
            name='ended',
        ),
        migrations.AddField(
            model_name='stream',
            name='past',
            field=models.BooleanField(default=False),
        ),
    ]
