# Generated by Django 2.2.9 on 2020-07-28 17:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stream', '0006_auto_20200728_0550'),
    ]

    operations = [
        migrations.AddField(
            model_name='code',
            name='valid',
            field=models.BooleanField(db_index=True, default=True),
        ),
        migrations.AlterField(
            model_name='code',
            name='email',
            field=models.CharField(blank=True, db_index=True, max_length=255, null=True, verbose_name='Email'),
        ),
    ]
