# Generated by Django 2.2.9 on 2020-09-09 16:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stream', '0007_auto_20200728_1747'),
    ]

    operations = [
        migrations.AddField(
            model_name='stream',
            name='cover_image',
            field=models.FileField(blank=True, null=True, upload_to='', verbose_name='фото для обложки'),
        ),
        migrations.AddField(
            model_name='stream',
            name='image',
            field=models.FileField(blank=True, null=True, upload_to='', verbose_name='Фото'),
        ),
    ]
