# Generated by Django 2.2.9 on 2020-11-02 16:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stream', '0008_auto_20200909_1631'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='code',
            unique_together={('code', 'stream')},
        ),
    ]
