# Generated by Django 2.2.9 on 2020-11-19 12:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stream', '0009_auto_20201102_1623'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stream',
            name='title',
            field=models.CharField(default='Untitled', max_length=1023, verbose_name='title'),
        ),
    ]
