# Generated by Django 2.2.9 on 2020-11-19 12:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stream', '0011_auto_20201119_1218'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stream',
            name='title',
            field=models.CharField(default='Untitled', max_length=2048, verbose_name='title'),
        ),
        migrations.AlterField(
            model_name='stream',
            name='url',
            field=models.CharField(blank=True, max_length=2048, null=True, verbose_name='URL'),
        ),
    ]
